### ISSUE TITLE
training pickle files

### ISSUE THREAD

**Issue by XinCynthia** [imatge-upc/wav2pix#1]
Hi
There is a need to use pickle files path in the config.yaml , could you please tell me what information the pickle files include? Thank you very much!

**Comment by ghost** [comment]
@xavigiro  I have the same question. Could you please share the structure of the information the pickle files include?

**Comment by jerinthomas1404** [comment]
Hey, @XinCynthia did you resolve this problem?

**Comment by XinCynthia** [comment]
> Hey, @XinCynthia did you resolve this problem?

not yet....

**Comment by ghost** [comment]
> Hey, @XinCynthia did you resolve this problem?
 First of all, you should have one folder for each subject. Inside the subject folders, I have two files with the same name. one for the audio with ".wav" extension which must be 1 sec. duration; and one for the image which must be gray. After preparing these folders, I executed generate_pickle.py and without any error, the pickle files are generated. However, the problem is that, when I try to run runtime.py, I get the following error:

```
Total amount of training samples: 60 faces | 60 audios 

Exception in user code:
------------------------------------------------------------
    data=json.dumps(msg),
    ....
    ret = torch._C._nn.mse_loss(expanded_input, expanded_target, _Reduction.get_enum(reduction))
    RuntimeError: reduce failed to synchronize: device-side assert triggered
```

**Comment by mandacduarte** [comment]
I am sorry but I just realized that the script to generate the pickle files were missing in the repo. We have just uploaded it and it would be straight forward to create the pickle files now. 
The script can be found under /scripts/generate_pickle.py 

The generated pickle files should point to the path of the audios and images(separated) that you intend to use during training and inference.  

Let us know if you have any problems on creating it.
